# Generated by Django 4.2.4 on 2023-08-03 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_utilisateur_rename_useradmin_administrateur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrateur',
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
