# Generated by Django 4.2.4 on 2023-08-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_utilisateur_administrateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='remarque',
            field=models.TextField(blank=True, null=True),
        ),
    ]
