# Generated by Django 4.2.4 on 2023-08-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_image_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrateur',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
