# Generated by Django 4.2.4 on 2023-08-04 18:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_comercial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Utilisateur',
            new_name='Tech',
        ),
    ]
