# Generated by Django 4.2.4 on 2023-08-04 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_rename_utilisateur_tech'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='post_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='post_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
