# Generated by Django 4.2.4 on 2023-08-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_image_post_date_order_post_date_order_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Nombre_doptimiseur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='acces_libre_le_jour_du_chantier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='acces_par_arriere_pour_passé',
            field=models.CharField(blank=True, choices=[('non', 'Non'), ('oui', 'Oui')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ajout_coffret_supp',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='analyse_modem',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='coffret_20_cm_disponible',
            field=models.CharField(blank=True, choices=[('non', 'Non'), ('oui', 'Oui')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='coffret_general_conforme',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='commentaire_technicien',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='condition_de_paiement',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='date_de_la_vt',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='differenciel_general',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='enphase',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='espace_pres_du_coffret_pour_onduleur_meme_piece',
            field=models.CharField(blank=True, choices=[('non', 'Non'), ('oui', 'Oui')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='etat_de_linstallation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='etat_du_toit',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='gaine_technique_present',
            field=models.CharField(blank=True, choices=[('non', 'Non'), ('oui', 'Oui')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='hauteur_sous_corniche',
            field=models.FloatField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='le_client_a_des_ardoise_tuiles_de_rechange',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='le_client_se_charge_de_gaine',
            field=models.CharField(blank=True, choices=[('non', 'Non'), ('oui', 'Oui')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='le_client_souheite_il_le_monitoring',
            field=models.CharField(blank=True, choices=[('non', 'Non'), ('oui', 'Oui')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='le_modem_est_il_dans_la_meme_piece_que_londuleur',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='le_projet_sera_finance_par',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='les_panneaux_doivent_etre_installes',
            field=models.CharField(blank=True, choices=[('non', 'Non'), ('oui', 'Oui')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='limiteur',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='modem_est_dans_la_meme_piece_que_londuleur',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='monitoring',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='nbr_dardoises_tuiles_rechange',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='nbr_de_metre_de_cable_a_prevoir',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='nbr_de_ppv',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='nbr_de_ppv_a_la_vt',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='nombre_de_metre_de_tranche',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='nombre_de_metres_entre_onduleur_et_panneaux',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='nombre_de_range_ppv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='nombre_pan_de_toiture',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='nombre_ppv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='nombre_ppv_toiture',
            field=models.FloatField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='nombre_ppv_toiture3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='nombres_de_metres_du_modem_a_lonuduleur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='onduleurs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='orientation',
            field=models.CharField(blank=True, choices=[('N', 'Nord'), ('NE', 'Nord-Est'), ('E', 'Est'), ('SE', 'Sud-Est'), ('S', 'Sud'), ('SW', 'Sud-Ouest'), ('W', 'Ouest'), ('NW', 'Nord-Ouest')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='passage_de_cable_nbre_piece_a_traverser',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ppv_en_chevalet_jardin',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ppv_en_paysage',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ppv_en_portait',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ppv_en_structure_jardin',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ppv_en_toiture_plate',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pressence_differentiel_general',
            field=models.CharField(blank=True, choices=[('non', 'Non'), ('oui', 'Oui')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='prevoir_un_differentiel_general',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='prevoir_un_limiteur',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='prise_de_terre_controle_5_derniere_annes',
            field=models.CharField(blank=True, choices=[('non', 'Non'), ('oui', 'Oui')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='remarque_du_chantier',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='si_de7m_nacelle',
            field=models.CharField(blank=True, choices=[('non', 'Non'), ('oui', 'Oui')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='si_pas_dacces_decrire_la_situation',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sous_toiture',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='statut_vt',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='test_de_la_terre',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='toiture',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tranche',
            field=models.CharField(blank=True, choices=[('non', 'Non'), ('oui', 'Oui')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='type_de_compteur',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='type_de_corniche',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='type_de_toitur_prevu',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='type_ppv',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='type_toiture_prevu_a_la_vt',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='vt_effectue_par',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
