# Generated by Django 4.2.4 on 2023-08-06 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_order_tuile_rechage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tuile_rechage',
        ),
    ]
