# Generated by Django 4.2.4 on 2023-08-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_order_tuile_rechage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='adress_de_facturation_adress',
        ),
        migrations.RemoveField(
            model_name='order',
            name='adress_de_facturation_cp',
        ),
        migrations.RemoveField(
            model_name='order',
            name='adress_de_facturation_localite',
        ),
        migrations.RemoveField(
            model_name='order',
            name='adress_de_livraison_adress',
        ),
        migrations.RemoveField(
            model_name='order',
            name='adress_de_livraison_cp',
        ),
        migrations.RemoveField(
            model_name='order',
            name='adress_de_livraison_localite',
        ),
        migrations.RemoveField(
            model_name='order',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='order',
            name='bic',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cp',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_de_signature',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_de_visite',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ean54145',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='forme_juridique',
        ),
        migrations.RemoveField(
            model_name='order',
            name='grd',
        ),
        migrations.RemoveField(
            model_name='order',
            name='localite',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ncompte',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ncompteur',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ngsm',
        ),
        migrations.RemoveField(
            model_name='order',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='order',
            name='nom_de_societe',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ntel',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ntva',
        ),
        migrations.RemoveField(
            model_name='order',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='order',
            name='remarque_1',
        ),
        migrations.AddField(
            model_name='order',
            name='tuile_rechage',
            field=models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], max_length=120, null=True),
        ),
    ]
