# Generated by Django 4.2.4 on 2023-08-06 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_order_adress_de_facturation_adress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tuile_rechage',
        ),
    ]
