# Generated by Django 4.2.4 on 2023-08-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_order_tuile_rechage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tuile_rechage',
            field=models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], max_length=120, null=True),
        ),
    ]
