# Generated by Django 4.2.4 on 2023-08-06 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_order_tuile_rechage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_et_prenom_du_client', models.CharField(max_length=200)),
                ('date_de_l_intallation', models.DateField()),
                ('equipe_qui_installe_toiture', models.TextField()),
                ('Raccordement_electiricien', models.CharField(max_length=200)),
                ('nom_sou_traitant', models.CharField(max_length=200)),
                ('description_de_la_panne', models.TextField(max_length=200)),
                ('heure_darrive', models.CharField(max_length=120)),
                ('heure_de_depart', models.CharField(max_length=120)),
                ('temps_intervention', models.CharField(max_length=120)),
                ('materiel_utilise', models.TextField()),
                ('remarque', models.TextField(blank=True, null=True)),
                ('ordre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.order')),
            ],
        ),
    ]
